### ISSUE TITLE
Dynamic `gen3c_dynamic_sdg.py` OOMs on H100 80GB with full offloading on first forward; README says ~43GB max

### ISSUE THREAD

**Issue by nbardy** [nv-tlabs/lyra#30]
## Summary

We are trying to run the upstream dynamic Lyra / GEN3C inference path on an H100 80GB GPU and are seeing an out-of-memory failure on the first diffusion forward, even with the full offloading flags recommended in the README.

The README says:

- Lyra was tested on H100 and A100
- full offloading should be possible with:
  - `--offload_diffusion_transformer`
  - `--offload_tokenizer`
  - `--offload_text_encoder_model`
  - `--offload_prompt_upsampler`
  - `--offload_guardrail_models`
  - `--disable_guardrail`
  - `--disable_prompt_encoder`
- “Maximum observed memory during inference with full offloading: ~43GB”

In our run, the first dynamic forward spikes to roughly:

- `74.16 GiB allocated`
- `78.06 GiB reserved`

and then fails trying to allocate another `440 MiB`.

This is on the first chunk, first trajectory, first real `pipeline.generate(...)` forward.

## Environment

- GPU: `NVIDIA H100 80GB HBM3`
- OS base: `ubuntu22.04`
- Python: `3.10`
- CUDA: `12.4`
- PyTorch: `2.6.0+cu124`
- Torchvision: `0.21.0`
- Torchaudio: `2.6.0`
- Transformer Engine: `1.12.0`
- flash-attn: tested both:
  - `2.7.4.post1`
  - `2.6.3`

We are using the upstream dynamic script:

```bash
torchrun --nproc_per_node=1 cosmos_predict1/diffusion/inference/gen3c_dynamic_sdg.py ...
```

and the upstream dynamic decode path via `sample.py` after latent generation.

## Input / inference setup

Dynamic inference setup:

- VIPE-formatted input
- normalized by upstream loader to:
  - `121` frames
  - `704x1280`
- `--foreground_masking`
- tested both:
  - `lyra_single_view` equivalent: no `--multi_trajectory`
  - `lyra_full` equivalent: with `--multi_trajectory`

Important: `multi_trajectory` is not the cause here. We also see the same failure in the single-view case on the first forward.

## Reproduction

The upstream README dynamic example is:

```bash
CUDA_HOME=$CONDA_PREFIX PYTHONPATH=$(pwd) torchrun --nproc_per_node=1 cosmos_predict1/diffusion/inference/gen3c_dynamic_sdg.py \
    --checkpoint_dir checkpoints \
    --vipe_path assets/demo/dynamic/diffusion_input/rgb/6a71ee0422ff4222884f1b2a3cba6820.mp4 \
    --video_save_folder assets/demo/dynamic/diffusion_output_generated \
    --disable_prompt_upsampler \
    --num_gpus 1 \
    --foreground_masking \
    --multi_trajectory
```

Our dynamic command is very close to that, with extra memory-saving flags added:

```bash
torchrun --nproc_per_node=1 cosmos_predict1/diffusion/inference/gen3c_dynamic_sdg.py \
    --checkpoint_dir <checkpoints> \
    --num_gpus 1 \
    --vipe_path <vipe_raw_dir> \
    --video_save_folder <latents_dir> \
    --foreground_masking \
    --guidance 0 \
    --negative_prompt "" \
    --disable_prompt_upsampler \
    --disable_guardrail \
    --offload_diffusion_transformer \
    --offload_tokenizer \
    --offload_text_encoder_model \
    --disable_prompt_encoder \
    --center_depth_quantile
```

We also tested with and without `--multi_trajectory`.

### 1. This is not ViPE or MoGe lingering on GPU

This is the dynamic path, so MoGe is not used.

VIPE is only precomputed input data here, not an active model. We instrumented the upstream code and saw:

- after input tensors move to CUDA: about `2.03 GiB`
- after render cache creation: about `4.09 GiB`

The large memory spike happens later during the actual diffusion forward.

### 2. This is not “all trajectories loaded at once”

`demo_multi_trajectory(...)` iterates trajectories sequentially.

Also, the single-view run fails in the same place.

### 3. This is not just the unsupported `flash_attn 2.7.4.post1` warning

With:

- `NVTE_FLASH_ATTN=1`
- `NVTE_FUSED_ATTN=0`

and `flash_attn==2.7.4.post1`, Transformer Engine warned that only `<=2.6.3` is supported and fell back to unfused attention, which OOMed even worse.

After pinning `flash_attn==2.6.3`, that unsupported-version issue went away, but the main first-forward OOM still remained.

So the flash version mismatch was real, but it was not the full explanation.

## Instrumentation / measured memory

We added memory logging around the main GEN3C stages in `gen3c_pipeline.py` and `gen3c_dynamic_sdg.py`.

For the latest failing single-view run with `flash_attn==2.6.3`:

- after input move to CUDA: `2.03 GiB`
- after render cache initial: `4.09 GiB`
- after tokenizer offload: `4.44 GiB`
- after diffusion network load: `17.92 GiB`
- before `_run_model`: `17.92 GiB`
- OOM inside `_run_model`: `74.16 GiB allocated / 78.06 GiB reserved`

Then:

```text
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 440.00 MiB
```

This points to the first real DiT forward, not setup, tokenization, or warp-cache creation.

## Attention backend observations

GEN3C diffusion appears to use Transformer Engine attention by default.

We observed:

- earlier failures on TE fused attention
- with `NVTE_FLASH_ATTN=1` and `NVTE_FUSED_ATTN=0`, TE no longer failed in fused attention
- with unsupported `flash_attn==2.7.4.post1`, TE fell back to unfused attention
- with supported `flash_attn==2.6.3`, we no longer see the unsupported-version warning, but we still see the high first-forward memory spike

## Question

Given the README guidance, we expected this to fit on an H100 80GB with full offloading.

Could you clarify:

1. Is the `~43GB` figure intended to apply to the dynamic `gen3c_dynamic_sdg.py` path at `121 x 704 x 1280`, or is it for a different inference configuration?
2. Is there an additional required runtime dependency or env setting for the intended low-memory H100 path?
3. Is there a recommended Transformer Engine / flash-attn / PyTorch version combination for H100 that differs from:
   - PyTorch `2.6.0+cu124`
   - Transformer Engine `1.12.0`
   - flash-attn `2.6.3`
4. Is there a recommended way to force the intended TE FlashAttention path for this inference stack?
5. Is there a known issue with the dynamic path’s first forward having much higher memory than the README reference?

## Additional context

We are happy to provide:

- the exact failing command line
- the patched memory logs
- full traceback output
- our measured stage-by-stage VRAM logs

The key issue is that this currently looks like:

- H100 should work according to the README
- full offloading is enabled
- but the first dynamic forward still peaks around `74-78GB`

which suggests either:

- we are still missing a setup detail
- or the README memory reference does not reflect this exact dynamic path

**Comment by sherwinbahmani** [comment]
Hi,

Thanks for the detailed feedback.

1. It is mainly for the static demo, but dynamic demo should not be that much higher memory consumption.
2. Not really.
3. It shouldn't make a big difference and the env setup from this repo should work fine.
4. I am not familiar with this.
5. I have not heard of this issue before and never encountered this issue.

Did you have a chance to try it with an A100? This is the GPU I was using to setup the repo, though H100 should also work fine. And does the static demo work for you without OOM?

Does GEN3C itself (https://github.com/nv-tlabs/GEN3C) with its dynamic video-to-video (Example 2: Video to Video Generation) setting work for you? We build upon that repo and if GEN3C does not work, this repo will also not work for you.

**Comment by nbardy** [comment]
Thanks, we checked the additional cases you asked about.

### 1. Static paths also OOM for us

We tested both:

1. Lyra static proof path:
   - `gen3c_single_image_sdg.py` + static Lyra decode
2. Standalone GEN3C static path:
   - `gen3c_single_image.py`

Results:

- `H100 80GB` static proof: OOM
- `A100 80GB` static proof: OOM
- `A100 80GB` standalone `gen3c_single_image.py`: OOM

So for us, this is not limited to the dynamic path, and it is not limited to Lyra decode either.

For example, on `A100 80GB`, the standalone `gen3c_single_image.py` path still reaches roughly:

- `78.50 GiB allocated`
- `78.54 GiB reserved`

before failing on the first real GEN3C forward.

### 2. Transformer Engine is definitely using FlashAttention

We added Transformer Engine debug logging and now see explicit lines such as:

```text
Available backends = {FlashAttention=True, FusedAttention=False, UnfusedDotProductAttention=False}
Selected backend = FlashAttention
Running with FlashAttention backend
So at this point, the issue does not appear to be “FlashAttention was not actually enabled”.
```

3. Standalone GEN3C static repro
The exact standalone static script also OOMs for us:
```
CUDA_HOME=$CONDA_PREFIX PYTHONPATH=$(pwd) python cosmos_predict1/diffusion/inference/gen3c_single_image.py \
  --checkpoint_dir checkpoints \
  --input_image_path <single_input_image> \
  --video_save_folder <output_dir> \
  --video_save_name test_single_image \
  --guidance 1 \
  --foreground_masking \
  --offload_diffusion_transformer \
  --offload_tokenizer \
  --offload_text_encoder_model \
  --offload_prompt_upsampler \
  --offload_guardrail_models \
  --disable_guardrail \
  --disable_prompt_encoder
```
In our run, this still hits the same large attention shape:

q_shape=(56320, 1, 32, 128)
and then OOMs on the first forward.

4. Current picture on our side
At this point, what we have confirmed is:

H100 80GB dynamic: OOM
H100 80GB static proof: OOM
A100 80GB static proof: OOM
A100 80GB standalone gen3c_single_image.py: OOM
Transformer Engine + FlashAttention: explicitly confirmed active
So the remaining question seems less about backend selection and more about why the first GEN3C forward is still reaching ~78GB on our side even when FlashAttention is selected.

**Comment by sherwinbahmani** [comment]
It looks like your machine can not even run GEN3C. Does it work with the base video model cosmos predict? (https://github.com/nvidia-cosmos/cosmos-predict1)

I have not heard of this issue and I can just recommend trying different conda environments and cuda drivers. It should requires much less than 80GB for just static GEN3C.

**Comment by nbardy** [comment]
Okay I have GEN3C running now and fitting in memory. I need to ablate what actually fixed it still but its done to 20GB memory with CFG off.

I ended up building a new image an turning off transformer engine for RMS and Attn and using flash attn 4 natively.
But also it has new cuda and torch versions, so it's not clear what dependencies conflict from the original repo was causing the issues. But seems like something with older versions and transformer engine blowing up attn costs.

I can post more as I dig in.

**Comment by nbardy** [comment]
I did a little bit of ablation and it seems root cause was some combination of transformer engine and cuda causing a fallback to non flash attention and blowing up memory.

I fixed it by disabling transformer engine and using flash attn 4 manually in all the code. It will be a load of work to dial this more exactly what went wrong, but I think transformer engine was claiming to be using flash attn but falling back somewhere.

I'll post what did and did work for anyone coming by this thread later looking for answers

Failed Requirements: (Taken from the repo)
```
base image:      nvidia/cuda:12.4.1-devel-ubuntu22.04
python:          3.10
torch:           2.6.0+cu124
torchvision:     0.21.0
torchaudio:      2.6.0
flash-attn:      2.6.3   (also tried 2.7.4.post1)
transformer-engine: 1.12.0
TORCH_CUDA_ARCH_LIST: 8.0;8.6;8.9;9.0+PTX
```

Successful Requirements: (Required bumping some other deps  and compiling for for newer torch)
```
base image:      pytorch/pytorch:2.11.0-cuda13.0-cudnn9-devel
python:          3.10
torch:           2.11.0+cu130
flash-attn:      flash-attn-4[cu13]==4.0.0b7
transformer-engine: 2.12.0
causal-conv1d:   1.6.1  (sm100-patched)
mamba:           v2.2.4 (built from source)
gsplat:          1.5.3
TORCH_CUDA_ARCH_LIST: 9.0+PTX
```

Including replacing the calls in lyra code to use manually calling flash attn 4 this came in at 20GB memory usage with CFG off
